print('Comparing Numbers'.center(50))
print(''.center(50, '-'))
num1 = int(input('Num1: '))
num2 = int(input('Num2: '))
print(''.center(50, '-'))
print('Less Than'.ljust(25), ':', num1 < num2)
print('Less or Equal Than'.ljust(25), ':', num1 <= num2)
print('Greater Than'.ljust(25), ':', num1 > num2)
print('Greater or Equal Than'.ljust(25), ':', num1 >= num2)
print('Equal'.ljust(25), ':', num1 == num2)
print('Different'.ljust(25), ':', num1 != num2)
print(''.center(50, '-'))
