# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-07 16:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import main.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
        ('accounts', '0001_initial'),
        ('condos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CondoProvider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(max_length=100, verbose_name='service')),
                ('condo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='condos.Condo', verbose_name='condominium')),
            ],
            options={
                'verbose_name': 'provider',
                'verbose_name_plural': 'providers',
            },
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='creation time')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='last update time')),
                ('identifier', models.CharField(blank=True, max_length=20, unique=True, verbose_name='id number')),
                ('identifier_type', models.CharField(blank=True, max_length=20, verbose_name='id type')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('I', 'Not specified'), ('N', 'Not Aplly')], default='N', max_length=1, verbose_name='gender')),
                ('phone', models.CharField(blank=True, max_length=20, validators=[main.validators.PhoneValidator], verbose_name='fixed phones')),
                ('celphone', models.CharField(blank=True, max_length=20, validators=[main.validators.PhoneValidator], verbose_name='mobile phones')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('services', models.CharField(max_length=200, verbose_name='services')),
                ('is_company', models.BooleanField(default=True, verbose_name='is company')),
                ('address', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='main.Address', verbose_name='address')),
                ('nationality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Country', verbose_name='nationality')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Tenant', verbose_name='tenant')),
            ],
            options={
                'verbose_name': 'provider',
                'verbose_name_plural': 'providers',
                'ordering': ['name', 'services'],
            },
        ),
        migrations.CreateModel(
            name='ProviderContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='creation time')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='last update time')),
                ('identifier', models.CharField(blank=True, max_length=20, unique=True, verbose_name='id number')),
                ('identifier_type', models.CharField(blank=True, max_length=20, verbose_name='id type')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('I', 'Not specified'), ('N', 'Not Aplly')], default='N', max_length=1, verbose_name='gender')),
                ('phone', models.CharField(blank=True, max_length=20, validators=[main.validators.PhoneValidator], verbose_name='fixed phones')),
                ('celphone', models.CharField(blank=True, max_length=20, validators=[main.validators.PhoneValidator], verbose_name='mobile phones')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=30, verbose_name='last name')),
                ('job_function', models.CharField(max_length=100, verbose_name='job function title')),
                ('job_function_desc', models.TextField(blank=True, verbose_name='job function description')),
                ('address', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='main.Address', verbose_name='address')),
                ('nationality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Country', verbose_name='nationality')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='providers.Provider', verbose_name='provider')),
            ],
            options={
                'verbose_name': 'provider contact',
                'verbose_name_plural': 'provider contacts',
                'ordering': ['first_name', 'last_name'],
            },
        ),
        migrations.AddField(
            model_name='condoprovider',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='providers.Provider', verbose_name='provider'),
        ),
    ]
