# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-23 16:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('condo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='condo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='condo.Condo'),
        ),
        migrations.AlterField(
            model_name='property',
            name='condo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='condo.Condo'),
        ),
    ]
