# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-07 16:29
from __future__ import unicode_literals

import accounts.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import main.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('main', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('element', models.CharField(max_length=100, verbose_name='object affected')),
                ('action', models.CharField(max_length=50, verbose_name='action')),
                ('detail', models.TextField(blank=True, verbose_name='detail')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='time')),
            ],
            options={
                'verbose_name': 'log',
                'verbose_name_plural': 'logs',
            },
        ),
        migrations.CreateModel(
            name='MultiTenantUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='creation time')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='last update time')),
                ('identifier', models.CharField(blank=True, max_length=20, unique=True, verbose_name='id number')),
                ('identifier_type', models.CharField(blank=True, max_length=20, verbose_name='id type')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('I', 'Not specified'), ('N', 'Not Aplly')], default='N', max_length=1, verbose_name='gender')),
                ('phone', models.CharField(blank=True, max_length=20, validators=[main.validators.PhoneValidator], verbose_name='fixed phones')),
                ('celphone', models.CharField(blank=True, max_length=20, validators=[main.validators.PhoneValidator], verbose_name='mobile phones')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='superuser status')),
                ('username', models.CharField(max_length=150, validators=[django.contrib.auth.validators.ASCIIUsernameValidator], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=30, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('address', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='main.Address', verbose_name='address')),
                ('groups', models.ManyToManyField(blank=True, related_name='user_set_mt', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('nationality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Country', verbose_name='nationality')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'ordering': ['tenant', 'username'],
            },
            managers=[
                ('objects', accounts.models.MultiTenantUserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True, verbose_name='name')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
            ],
            options={
                'verbose_name': 'tenant',
                'verbose_name_plural': 'tenants',
            },
        ),
        migrations.AddField(
            model_name='multitenantuser',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Tenant', verbose_name='tenant'),
        ),
        migrations.AddField(
            model_name='multitenantuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, related_name='user_set_mt', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
        migrations.AddField(
            model_name='log',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.MultiTenantUser', verbose_name='user'),
        ),
        migrations.AlterUniqueTogether(
            name='multitenantuser',
            unique_together=set([('username', 'tenant')]),
        ),
    ]
