# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-26 14:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('join', '0002_auto_20170726_1052'),
    ]

    operations = [
        migrations.AddField(
            model_name='join',
            name='zip_code',
            field=models.IntegerField(default=0),
        ),
    ]
