# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-07 16:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import main.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('condos', '0001_initial'),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='creation time')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='last update time')),
                ('identifier', models.CharField(blank=True, max_length=20, unique=True, verbose_name='id number')),
                ('identifier_type', models.CharField(blank=True, max_length=20, verbose_name='id type')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('I', 'Not specified'), ('N', 'Not Aplly')], default='N', max_length=1, verbose_name='gender')),
                ('phone', models.CharField(blank=True, max_length=20, validators=[main.validators.PhoneValidator], verbose_name='fixed phones')),
                ('celphone', models.CharField(blank=True, max_length=20, validators=[main.validators.PhoneValidator], verbose_name='mobile phones')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=30, verbose_name='last name')),
                ('contact_type', models.CharField(max_length=20, verbose_name='contact type')),
                ('address', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='main.Address', verbose_name='address')),
                ('nationality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Country', verbose_name='nationality')),
            ],
            options={
                'verbose_name': 'property contact',
                'verbose_name_plural': 'property contacts',
                'ordering': ['contact_type', 'first_name', 'last_name'],
            },
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='creation time')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='last update time')),
                ('name', models.CharField(max_length=200, verbose_name='property')),
                ('identifier', models.CharField(max_length=20, verbose_name='identifier')),
                ('owner_type', models.CharField(max_length=20, verbose_name='owner type')),
            ],
            options={
                'verbose_name': 'property owner',
                'verbose_name_plural': 'property owners',
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='creation time')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='last update time')),
                ('identifier', models.CharField(blank=True, max_length=50, verbose_name='property identifier')),
                ('zone', models.CharField(blank=True, max_length=100, verbose_name='property zone')),
                ('area', models.CharField(blank=True, max_length=100, verbose_name='property area')),
                ('number', models.CharField(max_length=100, verbose_name='property number')),
                ('property_type', models.CharField(max_length=100, verbose_name='property type')),
                ('proration', models.DecimalField(decimal_places=4, max_digits=6, verbose_name='property proration')),
                ('reference', models.TextField(blank=True, verbose_name='property location reference')),
                ('condo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='condos.Condo', verbose_name='condominium')),
            ],
            options={
                'verbose_name': 'property',
                'verbose_name_plural': 'properties',
                'ordering': ['zone', 'area', 'number'],
            },
        ),
        migrations.AddField(
            model_name='owner',
            name='proper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.Property', verbose_name='property'),
        ),
        migrations.AddField(
            model_name='contact',
            name='proper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.Property', verbose_name='property'),
        ),
    ]
