# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-07 19:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='reference',
        ),
        migrations.AddField(
            model_name='property',
            name='extras',
            field=models.TextField(blank=True, verbose_name='aditional information'),
        ),
    ]
