# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-07 16:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='creation time')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='last update time')),
                ('city', models.CharField(max_length=100, verbose_name='city')),
                ('zone', models.CharField(blank=True, max_length=100, verbose_name='zone')),
                ('zip_code', models.CharField(blank=True, max_length=15, verbose_name='zip code')),
                ('street', models.CharField(max_length=100, verbose_name='street')),
                ('number', models.CharField(max_length=100, verbose_name='number')),
                ('reference', models.TextField(verbose_name='reference')),
            ],
            options={
                'verbose_name': 'address',
                'verbose_name_plural': 'addresses',
                'ordering': ['county', 'city'],
            },
        ),
        migrations.CreateModel(
            name='Continent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='continent name')),
                ('code', models.CharField(max_length=2, unique=True, verbose_name='continent code')),
            ],
            options={
                'verbose_name': 'continent',
                'verbose_name_plural': 'continents',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='country name')),
                ('alpha2', models.CharField(max_length=2, unique=True, verbose_name='alpha-2 country code')),
                ('alpha3', models.CharField(max_length=3, unique=True, verbose_name='alpha-3 country code')),
                ('numeric', models.IntegerField(unique=True, verbose_name='numeric country code')),
                ('continent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Continent', verbose_name='continent')),
            ],
            options={
                'verbose_name': 'country',
                'verbose_name_plural': 'countries',
                'ordering': ['alpha2'],
            },
        ),
        migrations.CreateModel(
            name='County',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='county name')),
                ('code', models.CharField(max_length=10, verbose_name='county code')),
            ],
            options={
                'verbose_name': 'county',
                'verbose_name_plural': 'counties',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Dictionary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=50, verbose_name='aplication')),
                ('ttype', models.CharField(max_length=50, verbose_name='object type')),
                ('code', models.CharField(max_length=50, verbose_name='object code')),
                ('lang', models.CharField(max_length=10, verbose_name='languaje')),
                ('value', models.TextField(verbose_name='text')),
            ],
            options={
                'verbose_name': 'dictionary',
                'verbose_name_plural': 'dictionaries',
                'ordering': ['app', 'ttype', 'code', 'lang'],
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='county name')),
                ('division', models.CharField(max_length=20, verbose_name='division')),
                ('code', models.CharField(max_length=10, verbose_name='county code')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Country', verbose_name='country')),
            ],
            options={
                'verbose_name': 'region',
                'verbose_name_plural': 'regions',
                'ordering': ['code'],
            },
        ),
        migrations.AddField(
            model_name='county',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Region', verbose_name='region'),
        ),
        migrations.AddField(
            model_name='address',
            name='county',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.County', verbose_name='county'),
        ),
    ]
