# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-07 16:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import main.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('main', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminEmployee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='creation time')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='last update time')),
                ('employee_type', models.CharField(max_length=20, verbose_name='employee type')),
                ('job_function', models.CharField(max_length=100, verbose_name='job function title')),
                ('job_function_desc', models.TextField(blank=True, verbose_name='job function description')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Tenant', verbose_name='tenant')),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.MultiTenantUser', verbose_name='employee user')),
            ],
            options={
                'verbose_name': 'administration employee',
                'verbose_name_plural': 'administration employees',
            },
        ),
        migrations.CreateModel(
            name='Administration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='creation time')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='last update time')),
                ('identifier', models.CharField(blank=True, max_length=20, unique=True, verbose_name='id number')),
                ('identifier_type', models.CharField(blank=True, max_length=20, verbose_name='id type')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('I', 'Not specified'), ('N', 'Not Aplly')], default='N', max_length=1, verbose_name='gender')),
                ('phone', models.CharField(blank=True, max_length=20, validators=[main.validators.PhoneValidator], verbose_name='fixed phones')),
                ('celphone', models.CharField(blank=True, max_length=20, validators=[main.validators.PhoneValidator], verbose_name='mobile phones')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('name', models.CharField(blank=True, max_length=30, verbose_name='name')),
                ('logo', models.FilePathField(blank=True, path=None, verbose_name='logo image path')),
                ('address', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='main.Address', verbose_name='address')),
                ('nationality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Country', verbose_name='nationality')),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.Tenant', verbose_name='tenant')),
            ],
            options={
                'verbose_name': 'administration',
                'verbose_name_plural': 'administrations',
            },
        ),
    ]
